runtime: nodejs10

env_variables:
  API_URL: http://0.0.0.0:8080/api
  PORT: 8080
  DIALOGFLOW_TOKEN: 9a3251834022474ba63c0aa3d3115d85

handlers:
  # Any other requests are routed to index.html for angular to handle so we don't need hash URLs
  - url: /
    static_files: dist/index.html
    upload: dist/index.html
