import * as dotenv from 'dotenv';
import { writeFile } from 'fs';
import { argv } from 'yargs';

// This is good for local dev environments, when it's better to
// store a projects environment variables in a .gitignore'd file
dotenv.config();

// Would be passed to script like this:
// `ts-node set-env.ts --environment=dev`
// we get it from yargs's argv object
const env = argv.environment;

const targetPath = `./src/environments/environment.ts`;
const envConfigFile = `
// CAUTION: auto generated by \`set-env.ts\`
export const environment = {
  production: ${env === 'prod'},
  apiUrl: '${process.env.API_URL}',
  dialogflowToken: '${process.env.DIALOGFLOW_TOKEN}',
};
`;
writeFile(targetPath, envConfigFile, (err) => {
  if (err) {
    console.error(err);
  }

  console.log(`Output generated at ${targetPath}`);
});
