
// CAUTION: auto generated by `set-env.ts`
export const environment = {
  production: false,
  apiUrl: 'http://0.0.0.0:4001/api',
  files: 'http://0.0.0.0:4001/uploads',
  dialogflowToken: 'edebe774b6c4450b9db5c99ac5771071',
};
