runtime: nodejs10
env_variables:
  PORT: 8080
  MONGODB_HOST: 'banking-data-nzvtn.gcp.mongodb.net'
  MONGODB_DATABASE: 'api-data'
  MONGODB_USERNAME: 'root'
  MONGODB_PASSWORD: 'hera-0311'
  MONGODB_LOCATION: 'atlas'
